services:
  couchdb:
    image: couchdb:3.3
    container_name: obsidian-couchdb
    restart: unless-stopped
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: obsidian_admin_password_change_me
      COUCHDB_SINGLE_NODE: "true"
      COUCHDB_MAX_DOCUMENT_SIZE: "50000000"
    volumes:
      - ./data/couchdb:/opt/couchdb/data
    networks:
      - obsidian-network

  caddy:
    image: caddy:2-alpine
    container_name: obsidian-caddy
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy:/data
      - ./data/caddy/config:/config
    environment:
      - TAILSCALE_DOMAIN=${TAILSCALE_DOMAIN:-your-domain.com}
    networks:
      - obsidian-network
    depends_on:
      - couchdb

networks:
  obsidian-network:
    driver: bridge

