version: '3.8'

services:
  couchdb:
    image: couchdb:3.3
    container_name: obsidian-couchdb
    restart: unless-stopped
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: obsidian_admin_password_change_me
    volumes:
      - ./data/couchdb:/opt/couchdb/data
      - ./config/local.ini:/opt/couchdb/etc/local.d/local.ini
    networks:
      - obsidian-network

  caddy:
    image: caddy:2-alpine
    container_name: obsidian-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy:/data
      - ./data/caddy/config:/config
    environment:
      - TAILSCALE_DOMAIN=${TAILSCALE_DOMAIN:-your-domain.com}
    networks:
      - obsidian-network
    depends_on:
      - couchdb

networks:
  obsidian-network:
    driver: bridge
